export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#005236",
        "on-secondary-container": "#00714d",
        "surface": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#002113",
        "on-surface": "#0b1c30",
        "error": "#ba1a1a",
        "primary-container": "#2563eb",
        "inverse-on-surface": "#eaf1ff",
        "primary": "#004ac6",
        "on-primary-fixed": "#00174b",
        "surface-variant": "#d3e4fe",
        "inverse-surface": "#213145",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#4edea3",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary": "#ffffff",
        "surface-tint": "#0053db",
        "on-primary-container": "#eeefff",
        "on-tertiary-container": "#ffecec",
        "surface-bright": "#f8f9ff",
        "secondary": "#006c49",
        "on-tertiary-fixed": "#40000d",
        "inverse-primary": "#b4c5ff",
        "surface-container-high": "#dce9ff",
        "tertiary": "#ad0033",
        "surface-container-highest": "#d3e4fe",
        "on-surface-variant": "#434655",
        "secondary-container": "#6cf8bb",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#003ea8",
        "outline-variant": "#c3c6d7",
        "tertiary-fixed-dim": "#ffb2b7",
        "tertiary-container": "#d22348",
        "surface-container-low": "#eff4ff",
        "surface-dim": "#cbdbf5",
        "background": "#f8f9ff",
        "primary-fixed-dim": "#b4c5ff",
        "primary-fixed": "#dbe1ff",
        "on-background": "#0b1c30",
        "outline": "#737686",
        "on-primary": "#ffffff",
        "surface-container": "#e5eeff",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdadb",
        "on-tertiary-fixed-variant": "#92002a"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Pretendard"],
        "label": ["Pretendard"]
      }
    },
  },
  plugins: [],
}